version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3003:3000"
    depends_on:
      - postgres
      - fastapi

  fastapi:
    build: ./piccolo-fastapi
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./piccolo-fastapi:/usr/src/app
    ports:
      - 8008:8000
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: $POSTGRES_PORT
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - fastapi-piccolo-db:/var/lib/postgresql/data

volumes:
  fastapi-piccolo-db:

networks:
  default:
    name: fastapi-piccolo
